site_name: Spotify Ads List
site_url: https://spotify.piscinadeentropia.es
site_description: No more spotify ADS
copyright: License <a href="https://github.com/Isaaker/Spotify-AdsList/blob/main/LICENSE.txt">Creative Commons Attribution-ShareAlike 4.0 International Public License</a> | Reproduction and/or distribution, in whole or in part, and use in Artificial Intelligence is strictly prohibited
repo_url: https://github.com/Isaaker/Spotify-AdsList/

theme:
    name: material
    language: "en"
    logo: images/spotify_ads_list_logo.png
    favicon: images/spotify_ads_list_logo.png
    font:
        text: Ubuntu 
        code: IBM Plex Mono 
    icon:
      repo: fontawesome/brands/github
    features:
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.sections
      - navigation.top
      - search.suggest
    palette:
      - primary: green
      - accent: white

markdown_extensions:
  - attr_list
  - admonition
  - meta
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences

plugins:
  - awesome-pages:
      strict: false
  - redirects
  - search
  - mkdocs-simple-hooks:
      hooks:
        on_config: "hooks.on_config:deploy_hooks"
nav:
    - Home: index.md
    - Installation: docs_installation.md
    - Versions:
      - "Standard": "docs_standard.md"
      - "Pi-Hole": "docs_pihole.md"
      - "Dnsmasq": "docs_dnsmasq.md"
      - "Adguard": "docs_adguard.md"
    - Whitelist: docs_whitelist.md
    - Testing: docs_testing.md
    - Docs:
      - "F.A.Q": "docs_faq.md"
      - "How Spotify send ads?": "docs_how_spotify_ads.md"
      - "How adblockers work?": "docs_how_adblockers_work.md"
      - "Why to add aditional blocklists": "docs_why_add_more_blocklists.md"
    - About: 
      - "About": docs_about.md
      - "License": docs_license.md
      - "Contributing.md": docs_contributing.md
    - Report Bug: https://github.com/Isaaker/Spotify-AdsList/issues
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Isaaker/Spotify-AdsList/
