site_name: Spotify-AdsList
site_url: https://spotify.piscinadeentropia.es
site_description: No more spotify ADS
copyright: &copy; <a href="https://github.com/Isaaker/Spotify-AdsList/blob/main/LICENSE.txt">Creative Commons Attribution-ShareAlike 4.0 International Public License</a> | Reproduction and/or distribution, in whole or in part, and use in Artificial Intelligence is strictly prohibited

theme:
    name: material
    language: "en"
    logo: images/spotify_ads_list_logo.png
    favicon: images/spotify_ads_list_logo.png
    font:
        text: Ubuntu 
        code: IBM Plex Mono 
    features:
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.sections
      - navigation.top
      - navigation.footer
      - search.suggest
    palette:
      - primary: green
      - accent: white

markdown_extensions:
  - attr_list
  - admonition
  - meta
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences

plugins:
  - awesome-pages:
      strict: false
  - redirects
  - search
  - mkdocs-simple-hooks:
      hooks:
        on_config: "hooks.on_config:deploy_hooks"
  - rss:
      date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%Y-%m-%d"
      pretty_print: !ENV [PRETTY_RSS, false]
      length: 30
      match_path: "./*"

nav:
    - Home: index.md
    - Installation: installation.md
    - Versions:
      - "Standard": "standard.md"
      - "Pi-Hole": "pihole.md"
      - "Dnsmasq": "dnsmasq.md"
      - "Adguard": "adguard.md"
    - Whitelist: whitelist.md
    - Testing: testing.md
    - Docs:
      - "F.A.Q": "faq.md"
      - "How Spotify send ads?": "how_spotify_ads.md"
      - "How adblockers work?": "how_adblockers_work.md"
      - "Why to add aditional blocklists": "why_add_more_blocklists.md"
    - About: 
      - "About": about.md
      - "License": license.md
      - "Contributing.md": contributing.md
    - Report Bug: https://github.com/Isaaker/Spotify-AdsList/issues
    