name: Bug Report
description: Report a Bug
title: "[BUG]: "
labels: ["Bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for creating this issue, please tell us more about the problem.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: Example -> email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: "Please, select your platform."
      options:
        - Web App
        - App
        - API
        - TV
        - Carplay & Android auto
        - Smart Home Devices (such as speakers)
        - Other
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device
      description: "Please, enter your device name."
      placeholder: Example -> iPhone
    validations:
      required: true
  - type: input
    id: os_version
    attributes:
      label: OS & Version
      description: "Please, enter your device OS & Version."
      placeholder: Example -> MacOS (14.2.1)
    validations:
      required: true
  - type: input
    id: browser_version
    attributes:
      label: Browser & Version (If applicable)
      description: "Please, enter your Browser & Version (If applicable)."
      placeholder: Example -> Safari (17.2.1)
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true
  - type: textarea
    id: extra-info
    attributes:
      label: Extra Info about the bug
      description: Tell us extra info about the bug
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Isaaker/Ghost_Simulator_ES/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
        - label: I read the avaible Documentation
          required: true
        - label: I have checked that there is no issue on the same subject
          required: true
        - label: I have checked that my issue does not contain any relevant security data (Passwords, Secrets or Users)
          required: true
        - label: I have checked that my issue is not a Security Vulneability [Security Policy](https://github.com/Isaaker/Ghost_Simulator_ES/blob/main/SECURITY.md)
          required: true
