name: Testing Platform
description: Add a tested platform to the tested devices avaible in README.md
title: "[Testing]: "
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: "How can we get in touch with you if we need more info?"
      placeholder: Example -> email@example.com
    validations:
      required: false
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: "Please, select your platform."
      options:
        - Web App
        - App
        - API
        - TV
        - Carplay & Android auto
        - Smart Home Devices (such as speakers)
        - Other
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device
      description: "Please, enter your device name."
      placeholder: Example -> iPhone
    validations:
      required: true
  - type: input
    id: os_version
    attributes:
      label: OS & Version
      description: "Please, enter your device OS & Version."
      placeholder: Example -> MacOS (14.2.1)
    validations:
      required: true
  - type: input
    id: browser_version
    attributes:
      label: Browser & Version (If applicable)
      description: "Please, enter your Browser & Version (If applicable)."
      placeholder: Example -> Safari (17.2.1)
    validations:
      required: false
  - type: input
    id: date
    attributes:
      label: Testing Date
      description: "Please, enter your Testing Date -> Format: day/month/year."
      placeholder: Example -> 27/1/24
    validations:
      required: true
  - type: dropdown
    id: status
    attributes:
      label: Status
      description: "Please, select the testing result status."
      options:
        - OK
        - ERROR
    validations:
      required: true
  - type: dropdown
    id: list_type
    attributes:
      label: List Type
      description: "Please, select the list type."
      options:
        - Standard
        - Pi-hole
        - Dnsmasq
        - Adguard
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: "Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks."
      render: shell
  - type: textarea
    id: extra-info
    attributes:
      label: Extra Info about the testing
      description: "Tell us extra info about the testing"
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: "Please check if the following questions"
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
        - label: I read the avaible Documentation
          required: true
        - label: I have checked that there is no issue on the same subject
          required: true
        - label: I have checked that my issue does not contain any relevant security data (Passwords, Secrets or Users)
          required: true
        - label: I have checked that my issue is not a Security Vulneability [Security Policy](https://github.com/Isaaker/Ghost_Simulator_ES/blob/main/SECURITY.md)
          required: true
