name: MkDocs Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
    
jobs:
  linters:
    name: Repository linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938                    # @v4.2.0
      - name: Install NodeJs                                                               # Install Software NodeJs 
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b                  # @v4.0.3
        with:
          node-version: 16
      - name: Install repo-linter
        run: |
          npm install -g repolinter
      - name: Run Repo Linter
        run: |
          repolinter --rulesetFile cfg/repolint.json lint .      
  
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@44c470ffc35caa8b1eb3e8012ca53c2f9bea4eb5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_CONFIG: cfg/gitleaks.toml
          
  build:
    name: MkDocs Github Pages automatic deployment
    runs-on: ubuntu-latest
    needs: 
      - linters 
      - scan
    steps:
      - name: Checkout main
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938

      - name: Set up Python 3.9
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version: '3.9'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: MkDocs gh-deploy
        run: |
          git pull
          mkdocs gh-deploy -v