name: MkDocs Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
    
jobs:
  linters:
    name: Repository linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871                    # @v4.2.1
      - name: Install NodeJs                                                               # Install Software NodeJs 
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6                  # @v4.0.4
        with:
          node-version: 16
      - name: Install repo-linter
        run: |
          npm install -g repolinter
      - name: Run Repo Linter
        run: |
          repolinter --rulesetFile cfg/repolint.json lint .      
  
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@83373cf2f8c4db6e24b41c1a9b086bb9619e9cd3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_CONFIG: cfg/gitleaks.toml
          
  build:
    name: MkDocs Github Pages automatic deployment
    runs-on: ubuntu-latest
    needs: 
      - linters 
      - scan
    steps:
      - name: Checkout main
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871

      - name: Set up Python 3.9
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version: '3.9'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: MkDocs gh-deploy
        run: |
          git pull
          mkdocs gh-deploy -v