name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello, this is an automated message from the repository owner 🤖. \n Thank you for contributing to our project 😊. \n At this time, the project administrator is unavailable to review your changes or suggestions, so it may take some time for us to review your contribution. \n You can leave us a contact method in the description of your PR/Issue or in a comment below. If the administrator needs to contact you about your contribution, they will use this conversation or the contact information you share with us to get in touch. \n You can also contact the administrator at: [isaaker@piscinadeentropia.es](mailto:isaaker@piscinadeentropia.es) (this will not speed up the process, we are simply sharing this method in case you wish to use it). \n Thank you again for your PR/Issue."
        pr-message: "Hello, this is an automated message from the repository owner 🤖. \n Thank you for contributing to our project 😊. \n At this time, the project administrator is unavailable to review your changes or suggestions, so it may take some time for us to review your contribution. \n You can leave us a contact method in the description of your PR/Issue or in a comment below. If the administrator needs to contact you about your contribution, they will use this conversation or the contact information you share with us to get in touch. \n You can also contact the administrator at: [isaaker@piscinadeentropia.es](mailto:isaaker@piscinadeentropia.es) (this will not speed up the process, we are simply sharing this method in case you wish to use it). \n Thank you again for your PR/Issue."
