# Action to Lint open repositories for common issues
# Uses https://github.com/todogroup/repolinter

# Needs master/repolint.json

name: Repository Linter
on:
  workflow_dispatch:
      
jobs:
  launch-repolint:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}                                    # Only 1 instance at time 
    runs-on: ubuntu-latest
 
    steps:
    - name: Check out the code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683                    # @v4.2.2

    - name: Install NodeJs                                                               # Install Software NodeJs 
      uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a                  # @v4.2.0
      with:
        node-version: 16

    - name: Install repo-linter
      run: |
        npm install -g repolinter

    - name: Run Repo Linter
      run: |
        repolinter --rulesetFile cfg/repolint.json lint .      