name: SAST Semgrep
on:
  pull_request: {}
  push: {}
  workflow_dispatch:
jobs:
  sast_semgrep:
    permissions:                                                                         
      contents: read
    uses: ramshackle-code/sast_semgrep/.github/workflows/sast_semgrep.yml@17a2b599ce6930240aa6c2797eb121c8fe5badf4   #v1.0.2
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
